layout_spectrum: 0.4946237
color:
  saturation: 1
  brandStrength: 0.2307015
  lightness: 0.9982079
  rhythmicContrast: 0.06451613
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.7258065
name: Tay
